Arm sim
the-gearheads/2023Robot pull request #7
Opened 2023-02-12 04:56 UTC by AnotherUser12

really cool wrist and arm sim

2023-02-12 05:22 UTC, person4268 requested changes
Some other things to consider doing:
1. Refactor sim code into an ArmSim class
2. Annotate functions, if you'd like to spare the time to
3. Create a formatting commit, just right click and hit format document on all the files you've touched
4. Comment any checks that aren't immediately obvious why they're there

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/subsystems/Wrist.java
>          break;
should be `return;`, `break;` is for loops

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/subsystems/WristState.java
> +        return (this.getWristGoalLambda.apply(currentWrappedPos));
nit: unnecessary parentheses

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/subsystems/Wrist.java
> +    this.simVolts=pidval+ffval;
can you factor out all instances of stuff like this into its own private setVoltage function? just like you have have getPosition

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/controllers/OperatorController.java
> +    });
minor: should probably make this match all the other ones

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/controllers/Controllers.java
> +                                      joyName.toLowerCase().contains("keyboard") )) {
doesn't this make it impossible to drive a sim robot with a keyboard? you'd want that especially for vision sim

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/subsystems/Arm.java
> +        if((getPosition()>Units.degreesToRadians(0) && goal>0) || (getPosition()<-Units.degreesToRadians(180) && goal<0)){
ideally you'd comment why such checks are necessary or at least what they do

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/subsystems/Arm.java
> +    // SimBattery estimates loaded battery voltages
i don't see a SimBattery here

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/subsystems/Arm.java
> +    SmartDashboard.putData("Arm Sim", m_mech2d);
Consider naming this just "Arm", considering that publishing arm state is useful outside of sim

2023-02-12 05:22 UTC, person4268 commented on src/main/java/frc/robot/RobotContainer.java
> +    this.wrist=new Wrist(arm);
minor: for consistency, just do `wrist = new Wrist()`, no this

2023-02-12 05:25 UTC, person4268 commented on src/main/java/frc/robot/controllers/LogitechOperatorController.java
> +      }
what even

2023-02-12 05:27 UTC, person4268 commented on src/main/java/frc/robot/controllers/LogitechOperatorController.java
> -      return Math.abs(getArmAxis())>0.2;
also like just do Controllers.deadband(), you don't need this at all (unless you needed a different deadband, in which case just modify deadband to have a customizable one)

2023-02-12 21:40 UTC, person4268 commented on src/main/java/frc/robot/subsystems/MechRootWrapper.java
> +}
given how many classes you have, it's probably a good idea to put them all in their own subdirectory

2023-02-17 01:48 UTC, AnotherUser12 commented on src/main/java/frc/robot/controllers/Controllers.java
> +                                      joyName.toLowerCase().contains("keyboard") )) {
prolly unnecessary

2023-02-17 02:04 UTC, AnotherUser12 commented
probably works: merging - michael

2023-02-17 02:04 UTC, merged